### PR TITLE
Implement handle_command

### PR DESCRIPTION
**Pull request by dairyo**
Implement `handle_command` and its test.

Related PR: #81

### CODE REVIEW

**Comment by yongpingchen** [comment]
@shinsuke-nara I have the following questions: 
1. how to run tests? 
2. whether running tests in CI ?

**Comment by dairyo** [comment]
@yongpingchen Thank you for your comment:+1:

> 1. how to run tests?

I described how to execute tests in README.mkd.

> 2. whether running tests in CI ?

I fixed circle.yml to execute test in CI.
But we do not collect test results yet because I do not know how to output test results as a file. I will learn it and fix circle.yml in feature. I want to fix it in another PR. Could you wait it?

**Comment by yongpingchen** [comment]
@shinsuke-nara 
> I will learn it and fix circle.yml in feature. I want to fix it in another PR. Could you wait it?

I am okay. You can improve it in future.

**Review by yongpingchen — APPROVED** [review]
LGTM

**Pull request merged**
