### PR TITLE
Design onboard with thing

### PR DESCRIPTION
**Pull request by dairyo**
According to [this document](https://docs.google.com/document/edit?hgd=1&id=1CEDZA_Zcv5_IpkB3Am2BUarlAq3YoiTp8V0M-xwLR6c#heading=h.vyjjxnvp0j41), I fixed 'onboard_with_thing_id()` function.

#### Changes

* Add `thing_type`.
* Add `thing_propeties`
* Add `firmware_version`
* Add `layout_position`

### CODE REVIEW

**Review by rizakii — COMMENTED** [review]
why change `Kii Cloud` with `IOT Cloud`?

**Comment by dairyo** [comment]
@rizakii 

I followed the notation in thing-if iOSSDK like [this](https://github.com/KiiPlatform/thing-if-iOSSDK/blob/02a2d9c0d988428fd45e6221cbf17cdd6e08c6f1/ThingIFSDK/ThingIFSDK/OnboardWithVendorThingIDOptions.swift#L23)

Should I rollback?

**Comment by yongpingchen** [comment]
@shinsuke-nara Kii Cloud is better.

**Review by yongpingchen — CHANGES_REQUESTED** [review]
`onboard_with_vendor_thing_id` should be fixed too

**Comment by dairyo** [comment]
@yongpingchen @rizakii 

> @shinsuke-nara Kii Cloud is better.

OK, I will fix it. Should I fix on thing-if iOSSDK too?

**Comment by dairyo** [comment]
@rizakii @yongpingchen 

I fixed according to https://github.com/KiiPlatform/thing-if-ThingSDK/pull/79#issuecomment-294127711. Please confirm.

**Review by yongpingchen — APPROVED** [review]

**Comment by rizakii** [comment]
LGTM

**Pull request merged**
